// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace DevWinUIGallery;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"DevWinUIGallery.Views.HomeLandingPage", typeof(DevWinUIGallery.Views.HomeLandingPage)},
        {"DevWinUIGallery.Views.HatchPage", typeof(DevWinUIGallery.Views.HatchPage)},
        {"DevWinUIGallery.Views.TiledImageBrushPage", typeof(DevWinUIGallery.Views.TiledImageBrushPage)},
        {"DevWinUIGallery.Views.OutlineTextControlPage", typeof(DevWinUIGallery.Views.OutlineTextControlPage)},
        {"DevWinUIGallery.Views.WatermarkPage", typeof(DevWinUIGallery.Views.WatermarkPage)},
        {"DevWinUIGallery.Views.BlurAnimationPage", typeof(DevWinUIGallery.Views.BlurAnimationPage)},
        {"DevWinUIGallery.Views.TextMorphEffectPage", typeof(DevWinUIGallery.Views.TextMorphEffectPage)},
        {"DevWinUIGallery.Views.TextGlitchEffectPage", typeof(DevWinUIGallery.Views.TextGlitchEffectPage)},
        {"DevWinUIGallery.Views.TextBlockStrokeViewPage", typeof(DevWinUIGallery.Views.TextBlockStrokeViewPage)},
        {"DevWinUIGallery.Views.ParticlePage", typeof(DevWinUIGallery.Views.ParticlePage)},
        {"DevWinUIGallery.Views.WaveCirclePage", typeof(DevWinUIGallery.Views.WaveCirclePage)},
        {"DevWinUIGallery.Views.BubblePage", typeof(DevWinUIGallery.Views.BubblePage)},
        {"DevWinUIGallery.Views.GooeyPage", typeof(DevWinUIGallery.Views.GooeyPage)},
        {"DevWinUIGallery.Views.StepBarPage", typeof(DevWinUIGallery.Views.StepBarPage)},
        {"DevWinUIGallery.Views.GoToTopPage", typeof(DevWinUIGallery.Views.GoToTopPage)},
        {"DevWinUIGallery.Views.FlexPanelPage", typeof(DevWinUIGallery.Views.FlexPanelPage)},
        {"DevWinUIGallery.Views.HoneycombPanelPage", typeof(DevWinUIGallery.Views.HoneycombPanelPage)},
        {"DevWinUIGallery.Views.ElementGroupPage", typeof(DevWinUIGallery.Views.ElementGroupPage)},
        {"DevWinUIGallery.Views.CompareSliderPage", typeof(DevWinUIGallery.Views.CompareSliderPage)},
        {"DevWinUIGallery.Views.TransitioningContentControlPage", typeof(DevWinUIGallery.Views.TransitioningContentControlPage)},
        {"DevWinUIGallery.Views.CirclePanelPage", typeof(DevWinUIGallery.Views.CirclePanelPage)},
        {"DevWinUIGallery.Views.ClockPage", typeof(DevWinUIGallery.Views.ClockPage)},
        {"DevWinUIGallery.Views.DateTimePickerPage", typeof(DevWinUIGallery.Views.DateTimePickerPage)},
        {"DevWinUIGallery.Views.CalendarWithClockPage", typeof(DevWinUIGallery.Views.CalendarWithClockPage)},
        {"DevWinUIGallery.Views.RichTextFormatterPage", typeof(DevWinUIGallery.Views.RichTextFormatterPage)},
        {"DevWinUIGallery.Views.ProgressButtonPage", typeof(DevWinUIGallery.Views.ProgressButtonPage)},
        {"DevWinUIGallery.Views.TextBoxPage", typeof(DevWinUIGallery.Views.TextBoxPage)},
        {"DevWinUIGallery.Views.TileControlPage", typeof(DevWinUIGallery.Views.TileControlPage)},
        {"DevWinUIGallery.Views.PinBoxPage", typeof(DevWinUIGallery.Views.PinBoxPage)},
        {"DevWinUIGallery.Views.SelectorBarSegmentedPage", typeof(DevWinUIGallery.Views.SelectorBarSegmentedPage)},
        {"DevWinUIGallery.Views.ColorfulShimmingEffectPage", typeof(DevWinUIGallery.Views.ColorfulShimmingEffectPage)},
        {"DevWinUIGallery.Views.LongShadowTextBlockPage", typeof(DevWinUIGallery.Views.LongShadowTextBlockPage)},
        {"DevWinUIGallery.Views.CredentialHelperPage", typeof(DevWinUIGallery.Views.CredentialHelperPage)},
        {"DevWinUIGallery.Views.CompositionHelperPage", typeof(DevWinUIGallery.Views.CompositionHelperPage)},
        {"DevWinUIGallery.Views.FlipSidePage", typeof(DevWinUIGallery.Views.FlipSidePage)},
        {"DevWinUIGallery.Views.PagerControlPage", typeof(DevWinUIGallery.Views.PagerControlPage)},
        {"DevWinUIGallery.Views.AutoScrollViewPage", typeof(DevWinUIGallery.Views.AutoScrollViewPage)},
        {"DevWinUIGallery.Views.OpacityMaskViewPage", typeof(DevWinUIGallery.Views.OpacityMaskViewPage)},
        {"DevWinUIGallery.Views.ProgressBarPage", typeof(DevWinUIGallery.Views.ProgressBarPage)},
        {"DevWinUIGallery.Views.DividerPage", typeof(DevWinUIGallery.Views.DividerPage)},
        {"DevWinUIGallery.Views.ShieldPage", typeof(DevWinUIGallery.Views.ShieldPage)},
        {"DevWinUIGallery.Views.GravatarPage", typeof(DevWinUIGallery.Views.GravatarPage)},
        {"DevWinUIGallery.Views.GrowlPage", typeof(DevWinUIGallery.Views.GrowlPage)},
        {"DevWinUIGallery.Views.OptionsPageControlPage", typeof(DevWinUIGallery.Views.OptionsPageControlPage)},
        {"DevWinUIGallery.Views.RainbowFramePage", typeof(DevWinUIGallery.Views.RainbowFramePage)},
        {"DevWinUIGallery.Views.FileAndFolderPickerPage", typeof(DevWinUIGallery.Views.FileAndFolderPickerPage)},
        {"DevWinUIGallery.Views.StylesPage", typeof(DevWinUIGallery.Views.StylesPage)},
        {"DevWinUIGallery.Views.SwitchPresenterPage", typeof(DevWinUIGallery.Views.SwitchPresenterPage)},
        {"DevWinUIGallery.Views.ValidationPage", typeof(DevWinUIGallery.Views.ValidationPage)},
        {"DevWinUIGallery.Views.ExtensionPage", typeof(DevWinUIGallery.Views.ExtensionPage)},
        {"DevWinUIGallery.Views.ThemeManagerPage", typeof(DevWinUIGallery.Views.ThemeManagerPage)},
        {"DevWinUIGallery.Views.CheckUpdatePage", typeof(DevWinUIGallery.Views.CheckUpdatePage)},
        {"DevWinUIGallery.Views.InlineAutoCompleteTextBoxPage", typeof(DevWinUIGallery.Views.InlineAutoCompleteTextBoxPage)},
        {"DevWinUIGallery.Views.AllLandingsPage", typeof(DevWinUIGallery.Views.AllLandingsPage)},
        {"DevWinUIGallery.Views.HomeLandingsPage", typeof(DevWinUIGallery.Views.HomeLandingsPage)},
        {"DevWinUIGallery.Views.SettingsGroup", typeof(DevWinUIGallery.Views.SettingsGroup)},
        {"DevWinUIGallery.Views.SettingsControls", typeof(DevWinUIGallery.Views.SettingsControls)},
        {"DevWinUIGallery.Views.GeneralPage", typeof(DevWinUIGallery.Views.GeneralPage)},
        {"DevWinUIGallery.Views.OobePage", typeof(DevWinUIGallery.Views.OobePage)},
        {"DevWinUIGallery.Views.AwakePage", typeof(DevWinUIGallery.Views.AwakePage)},
        {"DevWinUIGallery.Views.ColorPickerPage", typeof(DevWinUIGallery.Views.ColorPickerPage)},
        {"DevWinUIGallery.Views.FancyZonesPage", typeof(DevWinUIGallery.Views.FancyZonesPage)},
        {"DevWinUIGallery.Views.PowerPreviewPage", typeof(DevWinUIGallery.Views.PowerPreviewPage)},
        {"DevWinUIGallery.Views.ImageResizerPage", typeof(DevWinUIGallery.Views.ImageResizerPage)},
        {"DevWinUIGallery.Views.KeyboardManagerPage", typeof(DevWinUIGallery.Views.KeyboardManagerPage)},
        {"DevWinUIGallery.Views.PowerRenamePage", typeof(DevWinUIGallery.Views.PowerRenamePage)},
        {"DevWinUIGallery.Views.PowerLauncherPage", typeof(DevWinUIGallery.Views.PowerLauncherPage)},
        {"DevWinUIGallery.Views.ShortcutGuidePage", typeof(DevWinUIGallery.Views.ShortcutGuidePage)},
    };
}
