name: Bug report
description: File a bug report.
title: "[Bug]: "
labels: []
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: NuGet package version
      options:
        - "DevWinUI 9.2.0"
        - "DevWinUI 9.1.0"
        - "DevWinUI 9.0.0"
        - "DevWinUI 8.9.2"
  - type: dropdown
    attributes:
      label: IDE
      description: Which Visual Studio versions did you see the issue on?
      multiple: true
      options:
        - "Visual Studio 2026-Insider"
        - "Visual Studio 2022"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
