// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DevWinUI_Template
{
    internal sealed partial class Vsix
    {
        public const string Id = "DevWinUI_Template.18eb89b1-bd1f-4e22-9196-6ea05b8ca61d";
        public const string Name = "DevWinUI Templates for WinUI";
        public const string Description = @"DevWinUI  Project Template, help you quickly create a new WinUI 3 App with DevWinUI  and MVVM Packages. We prepare your project with the following features: NavigationView, Custom TitleBar, HomeLandingPage and Settings Page (with Theme settings).
We also always use the latest version of WindowsAppSDK. 
Jump right into coding your project, and let us prepare project for you.";
        public const string Language = "en-US";
        public const string Version = "14.2.0";
        public const string Author = "Mahdi Hosseini";
        public const string Tags = "WindowsAppSDK, WinAppSDK, WinUI, DevWinUI, XAML, C#, Managed, winui3, winui 3, wasdk, windows app sdk, windowsappsdk, winuicommunity, settingsui, components, titlebar, navigationview, theme, mvvm, template, winui";
        public const bool IsPreview = false;
    }
}
