// https://github.com/jayfunc/BetterLyrics

namespace DevWinUI;

public partial class LyricData
{
    public List<LyricLine> LyricsLines { get; set; } = [];
    public bool AutoGenerated { get; set; } = false;
    public string WrappedOriginalText => string.Join("\n", LyricsLines.Select(line => line.PrimaryText));
    public bool IsWordByWord => LyricsLines.Any(x => x.IsPrimaryHasRealSyllableInfo);

    public LyricData()
    {
    }

    public LyricData(List<LyricLine> lyricsLines)
    {
        LyricsLines = lyricsLines;
    }

}
