global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using DevWinUI;
global using DevWinUIGallery.Common;
global using DevWinUIGallery.ViewModels;
global using DevWinUIGallery.Views;
global using static DevWinUIGallery.Common.AppHelper;
