using System.Globalization;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DevWinUI;

[Generator]
internal sealed partial class NavigationPageMapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var additionalFiles = context
            .AdditionalTextsProvider.Where(af => af.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase));

        var compilation = context.CompilationProvider;

        var combined = additionalFiles.Combine(compilation);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var (file, comp) = pair;
            Execute(spc, file, comp);
        });
    }

    private static void Execute(SourceProductionContext ctx, AdditionalText file, Compilation compilation)
    {
        var jsonText = file.GetText(ctx.CancellationToken)?.ToString();
        if (!TryDeserializeJson(jsonText ?? "", out var root))
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "GEN001",
                    "NavigationPageMappings Skipped",
                    $"Skipping {file.Path} because it's not valid JSON for NavigationPageMappings.",
                    "SourceGenerator",
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                Location.None));
            return;
        }

        var pageNames = new List<string>();
        foreach (var group in root.Groups)
        {
            foreach (var item in group.Items)
            {
                if (!string.IsNullOrEmpty(item.UniqueId))
                    pageNames.Add(item.UniqueId);
            }
        }

        if (pageNames.Count == 0)
            return;

        // Use Compilation's AssemblyName as root namespace
        var projectNamespace = compilation.AssemblyName ?? "GeneratedNamespace";

        // Generate source
        var sb = new StringBuilder();
        sb.AppendLine("// -----------------------------------------------------------------------------------------------------");
        sb.AppendLine("// | <auto-generated>                                                                                  |");
        sb.AppendLine("// |    This code was generated by source generator.                                                   |");
        sb.AppendLine("// |                                                                                                   |");
        sb.AppendLine("// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |");
        sb.AppendLine("// | </auto-generated>                                                                                 |");
        sb.AppendLine("// |                                                                                                   |");
        sb.AppendLine("// |                            -------------------------------------------                            |");
        sb.AppendLine("// |                            |                                         |                            |");
        sb.AppendLine($"// |                            |   Date Modified: {DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)}    |                            |");
        sb.AppendLine("// |                            |                                         |                            |");
        sb.AppendLine("// |                            -------------------------------------------                            |");
        sb.AppendLine("// -----------------------------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {projectNamespace};");
        sb.AppendLine("public partial class NavigationPageMappings");
        sb.AppendLine("{");
        sb.AppendLine("    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>");
        sb.AppendLine("    {");

        foreach (var pageName in pageNames)
            sb.AppendLine($"        {{\"{pageName}\", typeof({pageName})}},");

        sb.AppendLine("    };");
        sb.AppendLine("}");

        var fileName = $"NavigationPageMappings_{System.IO.Path.GetFileNameWithoutExtension(file.Path)}.g.cs";
        ctx.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryDeserializeJson(string jsonText, out DevWinUI.Root? root)
    {
        root = null;
        if (string.IsNullOrWhiteSpace(jsonText))
            return false;

        try
        {
            root = JsonSerializer.Deserialize(jsonText, typeof(Root), RootContext.Default) as Root;
            return root != null && root.Groups != null;
        }
        catch (JsonException)
        {
            // Skip invalid JSON without failing
            return false;
        }
    }
}
